### ISSUE TITLE
Add download link

### ISSUE THREAD

**Issue by saturnism** [GoogleCloudPlatform/stackdriver-zipkin#23]
There is no download link of the distribution. The package in GitHub releases is the source.

Recommend adding a Download section and refer to all release versions to this link:
https://mvnrepository.com/artifact/com.google.cloud.trace.adapters.zipkin/collector

**Comment by adriancole** [comment]
we can also add a maven central badge
https://github.com/jirutka/maven-badges

**Comment by denyska** [comment]
somehow release process has to be synchronized too: latest docker image doesn't conform with maven-central.

**Comment by kevinmdavis** [comment]
* I've previously tagged the `gcr.io/stackdriver-trace-docker/zipkin-collector:v0.2.0` docker image.
* I've just pushed the v0.2.0 release to Maven central so it be visible soon.

**Comment by kevinmdavis** [comment]
I've updated the README to include this information.
