### ISSUE TITLE
Add a GitHub repo description

### ISSUE THREAD

**Issue by steren** [GoogleCloudPlatform/stackdriver-zipkin#7]
The GitHub description on https://github.com/GoogleCloudPlatform/stackdriver-zipkin says "No description or website provided."
It should rather explain in a few word what this repo is.

**Comment by kevinmdavis** [comment]
Done.

I've set it to "Adapters for using Zipkin instrumentation with Stackdriver Trace" and linked to our [documentation](https://cloud.google.com/trace/docs/zipkin).
